 function Verge = import_VergenceData(filename)
%IMPORTFILE Import data from a text file
%  CONTINUOUSDATA7087 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  CONTINUOUSDATA7087 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  continuousdata7087 = importfile("/Volumes/server/Projects/Firefly-moving_firefly/Data/Pilot2-Human/Janna/09262020/config_lat_move_noFB/continuous_data_7087.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Sep-2020 20:07:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Status","Timestamp", "Mapping", "Context"	,"Confidence",	"Target Index",	"Mode"	,  "GazeX"	,  "GazeY"	,  "GazeZ"	,  "Gaze Distance"	,"CenterRX",	"CenterRY"	,"CenterRZ"	, "CenterLX", "CenterLY",  "CenterLZ",  "NormRX",   "NormRY"	,"NormRZ"	,"NormLX"	,"NormLY"	,"NormLZ"];
opts.VariableTypes = ["string", "double",   "string" , "double",      "double",      "double",      "double",  "double",   "double",   "double",   "double",          "double",     "double",     "double",   "double",   "double"  ,   "double",   "double",   "double",    "double",   "double",   "double",   "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Verge = readtable(filename, opts);

%% Convert to output type
Verge = table2array(Verge);
end