function discontinuousdata = import_discontinuous_human_VR(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DISCONTINUOUSDATA32 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  DISCONTINUOUSDATA32 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  discontinuousdata32 = importfile("/Volumes/server3/Projects/Firefly-moving_firefly/Data/Pilot2-Human/jp/different_on_times/lat_move_noFB/001/discontinuous_data_32.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Oct-2020 18:35:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 31);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["n", "max_v", "max_w", "ffv", "onDuration", "answer", "PosX0", "PosY0", "PosZ0", "RotX0", "RotY0", "RotZ0", "RotW0", "ffX", "ffY", "ffZ", "pCheckX", "pCheckY", "pCheckZ", "rCheckX", "rCheckY", "rCheckZ", "rCheckW", "distToFF", "rewarded", "timeout", "beginTime", "checkTime", "endTime", "waitTime", "ITI", "tau", "GAP", "Type", "NoiseTauTau", "NoiseTau", "RotNoiseGain", "VelNoiseGain", "nTaus", "minTau", "maxTau", "MeanDistance", "MeanTravelTime", "VelThreshold", "RotThreshold"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
% count(...,'.')+1 for number of variables

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
discontinuousdata = readtable(filename, opts);

% copy block parameters to each trial
blkprs_indx = find(strcmpi('type',discontinuousdata.Properties.VariableNames));
totalprs = length(discontinuousdata.Properties.VariableNames);
for i = blkprs_indx:totalprs
    discontinuousdata(:,i) = discontinuousdata(1,i);   
end

%% Convert to output type
discontinuousdata = table2array(discontinuousdata);
end